services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    volumes:
      - ./client:/app/frontend
      - frontend_node_modules:/app/frontend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
      - backend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development

volumes:
  frontend_node_modules:
  backend_node_modules:
